# Generated by Django 3.2.2 on 2021-07-06 15:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_must be unique'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('get_clean', django.db.models.manager.Manager()),
            ],
        ),
    ]
